### ISSUE TITLE
Issue with LibreOffice

### ISSUE THREAD

**Issue by hiraymond** [Sayi/poi-tl#834] opened 2022-08-08 04:42 UTC
### Issue description
When opening the generated file with LibreOffice, the layout is missing

### poi-tl version
1.12.0

**Comment by hiraymond** [comment] 2022-08-08 06:08
It seems to be happening when I fetch a text data with multiple lines from database

**Comment by Sayi** [comment] 2022-08-08 06:24
Can you provide the template.docx and output.docx?

**Comment by hiraymond** [comment] 2022-08-08 06:45
template: [test.docx](https://github.com/Sayi/poi-tl/files/9279395/test.docx)
output: [Initial_NPF_101_1234567.docx](https://github.com/Sayi/poi-tl/files/9279397/Initial_NPF_101_1234567.docx)

**Comment by Sayi** [comment] 2022-08-08 07:10
I can't reproduce the problem using the template you provided.

JUnit:
```java
    @Test
    public void test() throws IOException {
        Map<Object, Object> model = new HashMap<>();
        model.put("studyTitle", "test\ntest");
        model.put("protoNo", "123456");
        model.put("studyPlace", "International");
        model.put("studyType", "A");
        XWPFTemplate.compile("test.docx").render(model).writeToFile("out_834.docx");
    }
```

libreoffice(v7.2.0.4):
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1394854/183360071-9a741560-05df-47c2-8f76-07db37eba4b3.png">

**Comment by hiraymond** [comment] 2022-08-08 07:33
As I said, I am fetching the data from database

**Comment by hiraymond** [comment] 2022-08-08 07:34
![image](https://user-images.githubusercontent.com/60968540/183364282-b3e815e6-1ee9-482b-9bb7-154f67cdd79e.png)
using mariaDB with this configuration

**Comment by Sayi** [comment] 2022-08-08 08:07
I think it doesn't matter where the data comes from...

**Comment by hiraymond** [comment] 2022-08-08 08:15
I think there is a slight difference
from database:![image](https://user-images.githubusercontent.com/60968540/183371611-8962a3af-0de6-4e2e-8594-f84872ab08c7.png)
Using "\n" :![image](https://user-images.githubusercontent.com/60968540/183371653-7b9d260d-5fb4-4b2b-ade0-ca5677af180b.png)
I have tried model.put("studyTitle", "test\ntest"); and it works perfectly, but when I fetch it from database the bug appears

**Comment by Sayi** [comment] 2022-08-08 08:25
Can you provide the sql of the table structure and data?

**Comment by hiraymond** [comment] 2022-08-08 08:32
maybe you can try model.put("studyTitle", "test\r\ntest");

**Comment by Sayi** [comment] 2022-08-08 09:10
It is indeed a problem with \r.

Yes, it is indeed the problem of \r. It can be opened normally in Microsoft office and Mac Pages, but libreoffice cannot.

**Comment by Sayi** [comment] 2022-11-14 06:14
Support `\r\n` and will be released in the next release.

**Closed by Sayi** 2022-11-14 06:14 UTC
